BABEL_DEFAULT_LOCALE = "en_GB"

HOME_URL = "https://ekitabu.com"
HOME_TITLE = "Ekitabu"

[kerko.meta]

title = "Evidence Library – Ekitabu"
google_analytics_id = ""

[kerko.link_groups]

[[kerko.link_groups.breadcrumb_base]]
text = "Ekitabu"
type = "url"
url = "https://ekitabu.com"

[[kerko.link_groups.breadcrumb_base]]
text = "Evidence Library"
type = "endpoint"
endpoint = "kerko.search"

[kerko.features]

download_attachment_new_window = true
open_in_zotero_app = true
open_in_zotero_web = true
print_item = true
print_results = true
results_abstracts = true
results_abstracts_max_length = 500
results_abstracts_max_length_leeway = 40
relations_initial_limit = 50

[kerko.search]

result_fields = ["id", "attachments", "bib", "data", "preview", "url"]
whoosh_language = "en"

[kerko.templates]

base = "kerkoapp/base.html.jinja2"
layout = "kerkoapp/layout.html.jinja2"
search_item = "kerkoapp/search-item.html.jinja2"
item = "kerkoapp/item.html.jinja2"
atom_feed = "kerkoapp/atom.xml.jinja2"
search = "search/search.html.jinja2"

[kerko.zotero]

locale = "en-GB"
batch_size = 20
# CAUTION: The URL's query string (after the '?') must be changed after any edit
# to the CSL style, otherwise zotero.org might still use a previously cached
# version of the file.
csl_style = "https://docs.opendeved.net/static/dist/csl/eth_apa.xml?202012301815"

item_exclude_re = "^_exclude$"

child_include_re = "^(_publish)|(publishPDF)$"
child_exclude_re = ""

[kerko.facets]

[kerko.facets.tag]
enabled = false

[kerko.facets.link]
enabled = false

[kerko.facets.item_type]
enabled = false

# [kerko.facets.featured]
# enabled = true
# type = "collection"
# collection_key = "JUDM2WBF"
# filter_key = "featured"
# title = "Featured publisher"
# weight = 10
# initial_limit = 15
# initial_limit_leeway = 5

# [kerko.facets.pubtype]
# enabled = true
# type = "collection"
# collection_key = "NEH6ARC4"
# filter_key = "pubtype"
# title = "Publication type"
# weight = 20
# initial_limit = 5
# initial_limit_leeway = 2

# [kerko.facets.theme]
# enabled = true
# type = "collection"
# collection_key = "QK8NXPKZ"
# filter_key = "theme"
# title = "Theme"
# weight = 30
# initial_limit = 10
# initial_limit_leeway = 2

# [kerko.facets.location]
# enabled = true
# type = "collection"
# collection_key = "94GNF2EB"
# filter_key = "location"
# title = "Location"
# weight = 50
# initial_limit = 5
# initial_limit_leeway = 2

[kerko.performance]

whoosh_index_memory_limit = 64

[kerkoapp.proxy_fix]

enabled = false
x_for = 1
x_proto = 1
x_host = 0
x_port = 0
x_prefix = 0

# footer
[footer]
contactUsButtonLink = "https://www.ekitabu.com/contact"
[[footer.links]]
text = "Privacy Policy"
url = "https://www.ekitabu.com/privacy-policy"
[[footer.links]]
text = "Terms of Service"
url = "https://www.ekitabu.com/terms-of-service"

# contact
[[footer.contact.items]]
field = "Email"
value = "support@ekitabu.com"
[[footer.contact.items]]
field = "Phone"
value = "+254 740 524629"
[[footer.contact.items]]
field = "Office Address"
value = """Rainbow Tower, 5th Floor
32 Muthithi Road, Westlands
Nairobi, Kenya"""

# navbar
[navbar]
[[navbar.items]]
text = "About"
url = "https://www.ekitabu.com/about"
[[navbar.items]]
text = "Programs"
url = "https://www.ekitabu.com/programs"
# [[navbar.items]]
# text = "Evidence Library"
# url = "/"
[[navbar.items]]
text = "Content"
url = "https://www.ekitabu.com/content"
[[navbar.items]]
text = "Impact"
url = "https://www.ekitabu.com/impact"
# [[navbar.items]]
# text = "Contact Us"
# url = "https://opendeved.net/contact-us/"

[posthog]
POSTHOG_API_KEY = "empty"
POSTHOG_API_HOST = "empty"
